# To test meteoclimatic update:
#    python ../wfrender.py -f meteoclimatic.yaml -s ../../wfcommon/config/settings.yaml

init:
    storage: !service
        name: storage
        instance: !include
            path: ../../wfcommon/config/storage.yaml

renderer: !http
    root: !meteoclimatic
        id: YOUR_STATION_ID
        storage: !service
            name: storage

logging:
    level: debug
    filename: !user
        choices:
            root: /var/log/wfrender.log
            default: wfrender.log

    ## By default wfrog uses a Rotating file handler. To set up different handlers
    ## uncomment the following section. (Warning: does not work under python > 2.7)
    #handlers:
    #    default:
    #        level: debug
    #
    #        handler: !include
    #            path: ../../wfcommon/config/loghandler.yaml
    #            variables:
    #                process: wfrender
    #
    #    ## Uncomment to receive mail on critical events
    #    #mail:
    #    #    level: critical
    #    #    handler: !include
    #    #        path: ../../wfcommon/config/mailloghandler.yaml



