storage: !user
    choices:
        root: !csv
            path: /var/lib/wfrog/wfrog.csv
        default: !csv
            path: data/wfrog.csv

## You may use sqlite3 instead of csv.
## (1) comment out the above lines and uncomment below,
## (2) install pysqlite2 and dependencies,
## (3) create the database and its tables:
##     to this end, copy the schema somewhere
#$ cp /usr/lib/wfrog/database/db-sqlite3.sql /tmp/
##     edit it to enable extra sensor that you may have
#$ nano /tmp/db-sqlite3.sql
##     create the table
#$ sqlite3 /var/lib/wfrog/wfrog.sdb < /tmp/db-sqlite3.sql # as root
#$ sqlite3 ~/.wfrog/data/wfrog.sdb < /tmp/db-sqlite3.sql # as user
## (4) in case, use the  csv2sqlite3  script to
##    transfer meteo data from the CVS file to the SQL file
#$ /usr/lib/wfrog/database/csv2sqlite3 /var/lib/wfrog/wfrog.csv /var/lib/wfrog/wfrog.sql

#storage: !user
#    choices:
#       root: !sqlite3
#           database: /var/lib/wfrog/wfrog.sdb
#       default: !sqlite3
#           database: data/wfrog.sdb

## Similarly you may use other databases as backends.

#storage: !firebird { database: 'localhost:/var/lib/firebird/2.0/data/wfrog.db',
#                     user: sysdba,
#                     password: masterkey }

#storage: !mysql { database: wfrog,
#                  host: localhost,
#                  user: root,
#                  password: root }
