from: !csv
    path: /tmp/wfrog.csv

to: !mysql { database: wfrog,
             host: localhost,
             user: root,
             password: root }

logging:
    level: info
    handlers:
        default:
            level: debug
            handler: !!python/object/new:logging.FileHandler
                kwds:
                    filename: storagecopy.log


